services:
  postgres:
    image: postgres:latest
    ports:
      - "7777:5432" 
    environment:
      POSTGRES_DB: mydatabase  
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: